### ISSUE TITLE
系统的流程模块

### ISSUE THREAD

**Issue by afish177** [zxiaozhou/skillfull-cloud#7]
看了下 大佬的开源代码 流程这块目前是 不会开源嘛 想学习下

**Comment by zxiaozhou** [comment]
非常抱歉，只会开源基础功能。同时基础的大改动近期会完成，还原继续关注

**Comment by afish177** [comment]
是有偿 还是 不会开放呢&nbsp;
&nbsp;


浮生ふ物语
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月16日(星期六) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zxiaozhou/skillfull-cloud] 系统的流程模块 (Issue #7)





 
非常抱歉，只会开源基础功能。同时基础的大改动近期会完成，还原继续关注

**Comment by afish177** [comment]
> @afish177 具体说需要授权，毕竟抽时间出来整东西，是需要花费很多经历的。开源部分只能满足一般需求。

嗯嗯 明白了 大概授权价格是？ 我想了解下 有群 或者 别的联系方式吗

**Comment by afish177** [comment]
> 嗯嗯 明白了 大概授权价格是？ 我想了解下 有群 或者 别的联系方式吗

**Comment by zxiaozhou** [comment]
@afish177 首页有开源版的群，授权的话因为东西没做完也不好公布出来，授权需要单独拉人进群。整个系统大概会是几万。东西涉及有点多。主要还是面向企业(没打算面向个人，目前淘宝店铺还在处理，企业设计到会开发票等等，还有一些比如花呗分期啥的)，但授权肯定只能用于自己项目，不能封装后做出同类型的产品出来卖

**Comment by zxiaozhou** [comment]
@afish177 首页有开源版的群，授权的话因为东西没做完也不好公布出来，授权需要单独拉人进群。整个系统大概会是几万。东西涉及有点多。主要还是面向企业(没打算面向个人，目前淘宝店铺还在处理，企业设计到会开发票等等，还有一些比如花呗分期啥的)，但授权肯定只能用于自己项目，不能封装后做出同类型的产品出来卖

**Comment by afish177** [comment]
个人 其实对流程 模块 倒是很感兴趣  不能单独这块 有偿面向个人吗

**Comment by afish177** [comment]
嗯嗯 明白 我个人是对流程这块感兴趣

**Comment by afish177** [comment]
我记得 去年 我就关注了 哈哈哈 后面大佬 重新建了新得 老得代码 都删了

**Comment by zxiaozhou** [comment]
@afish177 你先加开源群，开源版出来了，pro版本肯定先弄完了。其实这个项目pro版本一直在用，但是都是用在一些私有项目上的。最近几天一直在处理网关全局动态鉴权。也差不多完了。剩下就是调度中心，搞了再去搞动态表单(动态表单弄了流程基本就完了)

**Comment by afish177** [comment]
嗯嗯 好得 我先入群吧
